name: flutter_crazy_fortune_wheel
description: "A Fortune wheel with different styles and animations."
version: 1.0.1
homepage: https://github.com/ikbendewilliam/flutter_crazy_fortune_wheel

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  flutter_shaders: ^0.1.0
  flutter_shader_snap: ^0.0.3

flutter:
  shaders:
    - packages/flutter_shader_snap/shaders/split_snap_effect_shader.glsl
